force-app/main/default/objects/Auto__c/Auto__c.object-meta.xml
<CustomObject>
    <label>Auto</label>
    <nameField>
        <label>Nombre de Auto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Autos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Auto__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fiat</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>VW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoController.cls
public with sharing class AutoController {

    @AuraEnabled
    public static void saveAuto2(String marca, String Name) {
        Auto__c auto = new Auto__c( Marca__c = marca, Name = name);
        Database.upsert(auto);
    }

    @AuraEnabled(cacheable=true)
    public static List<Auto__c> getAutos(String marca) {

        String query = 'SELECT Id, Name, Marca__c FROM Auto__c ';
        if ( String.isNotBlank(marca)) {
            query += ' WHERE Marca__c = :marca ';
        }
        System.debug(query);
        return Database.query(query);
    }

}